apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-flask-devops-demo
  labels:
    app: {{ .Release.Name }}-flask-devops-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-flask-devops-demo
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-flask-devops-demo
    spec:
      containers:
        - name: flask-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
